# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SMNApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'FrameworkClient', :path => '../FrameworkClient'
  pod 'NextResponderTextField' => '2.0.1'
  pod 'ObjectMapper' => '2.2'
  pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :branch => 'master'


  # Pods for SMNApp

  target 'SMNAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SMNAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
